### ISSUE TITLE
Captcha not showing up

### ISSUE THREAD

**Issue by mtvcdm** [pump19/pump19.eu#22]
It was noticed in chat today that, when clicking a link for codefall, the screen told you that you're one click away from claiming the code as typical, but the 'not a robot' checkmark doesn't show up along with it, and without the verification, the codes can't actually be claimed by anyone.

**Comment by pyrige** [comment]
It seems the security settings for embedding the captcha scripts were a bit too restrictive.
Now it should work again for everyone
