### ISSUE TITLE
Cant seem to connect to the site with twitch

### ISSUE THREAD

**Issue by coolbond1** [pump19/pump19.eu#6]
tried to add some codes i had lying around but it seems i cant log in whenever i click the connect to twitch button it loads but then it goes straight back to the same page

**Comment by pyrige** [comment]
It seems Twitch authentication is broken indeed.
They might have changed something recentlish.
I'll look into it.

**Comment by pyrige** [comment]
I indeed needed to change some minor things. In the process I changed a bit more than I needed to.
So I guess login is fixed but some other things might be a bit broken now ;)
